config/routes.rb
Omrails::Application.routes.draw do

  root :to => "pages#home"
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  get 'about' => 'pages#about'
  get 'pins/updateLikes'
  put 'pins/updateLikes'

  resources :pins

  devise_for :users
  ActiveAdmin.routes(self)
  resources :users
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/like.rb
class Like < ActiveRecord::Base
  attr_accessible :pin_id, :user_id, :rating
  
  # Associations
  belongs_to :user
  has_one :pin

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description, :image, :likeCount
  
  # Validation
  validates :description, presence: true
  validates :user_id, presence: true
  validates_attachment :image, content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
  														 size: {less_than: 5.megabytes }
  														 
  # Associations
  has_attached_file :image
  belongs_to :user
  has_many :likes
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :likedPins
  # attr_accessible :title, :body
  
  has_many :pins
  has_many :likes
  
  def fname
    self.name.split(/\s+/, 1+1)[0...1].join(' ')
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery
  
  def after_sign_in_path_for(resource)
	  pins_path
 	end
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!
  
  def main
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  	@pins = Pin.order('created_at DESC')
  	@pinsLikes = Pin.order('like_count DESC')
  	if user_signed_in?
  		@likedPins = User.find(current_user.id).likes;
  	end
  end
  
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :authenticate_user!, except: [:updateLikes, :show]
  
  # GET /pins
  # GET /pins.json
  def index
    @myPins = current_user.pins.order('created_at DESC')
    @otherPins = Pin.where(['user_id <> ?', current_user.id])
    @pin = current_user.pins.new
    @likedPins = User.find(current_user.id).likes;

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @pin = current_user.pins.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(params[:pin])
    @pin["like_count"] = 0

    respond_to do |format|
      if @pin.save
        format.html { redirect_to action: 'index', notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = current_user.pins.find(params[:id])
    @pin["like_count"] = 0

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to action: 'index', notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
  
  def updateLikes
  	@pin = Pin.find(params[:id])
  	
  	if Like.where(:user_id => current_user.id,:pin_id => params[:id]).count > 0
  		@like = Like.where(:user_id => current_user.id,:pin_id => params[:id])
  		@like.update_all(:rating => (params[:like]) ? 1 : -1)
  	else
  		@like = Like.new
  		@like.user_id = current_user.id
  		@like.pin_id = params[:id]
  		@like.rating = (params[:like]) ? 1 : -1
  		@like.save
  	end
  	
  	@pin["like_count"] = Like.where(:pin_id => params[:id], :rating => 1).count
  	
    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.json { head :no_content }
      else
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
		:user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/pages_helper.rb
module PagesHelper

end

app/helpers/pins_helper.rb
module PinsHelper

end

app/views/dashboard/main.html.erb
<h1>User Dashboard</h1>
<p><%= link_to "Get started", pins_path %></p>

app/views/layouts/_footer.html.erb
<div class="container">
	<small>Did Not Know That &copy; <%= Time.now.year %> <%=link_to "Derrick Showers", "http://derrickshowers.com" %></small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%=link_to image_tag("logo25x25.png", :alt => "Logo") + " Did Not Know That", root_path ,class: "brand" %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <ul class="nav pull-right">
        	<li><%=link_to "About", about_path %></li>
        	<li><%=link_to "Login", new_user_session_path, :class => "visible-phone" %></li>
        	<% if user_signed_in? %>
        		<li><%=link_to "Profile", edit_user_registration_path %></li>
        		<li><%=link_to "My Did-Not-Know-Thats", pins_path %></li>
        		<li><%=link_to "Not " + current_user.fname + "? Logout", destroy_user_session_path, method: :delete %></li>
        	<% else %>
        		<li><%=link_to "Sign Up", new_user_registration_path %></li>
        	<% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<% 
	# Special header for homepage - needs to be here to get out of the 
	# container tags.
%>
<% if current_page?(root_path) %>
	<div id="homepageHeader">
		<div class="container">
			<h2>Share Those "Did Not Know That" Moments</h2>
			<div class="row">
				<div class="span4 text-center">
					<div id="step1" class="homeSteps"></div>
					<p>You have a sudden moment. You read something. Someone tells you something. Perhaps it comes to you in a dream. After you've realized what has just occurred - you might just happen to say... <strong>"Did Not Know That."</strong></p>
				</div>
				<div class="span4 text-center">
					<div id="step2" class="homeSteps"></div>
					<p>So you <strong>log onto the interwebs</strong>, whether it be from your laptop, tablet or mobile device - and it feels so much better to publicly show-off this very important piece of information.</p>
				</div>
				<div class="span4 text-center">
					<div id="step3" class="homeSteps"></div>
					<p>Sharing IS caring - why reap all the benefits of this sudden "Aha!" moments without allowing others the opportunity as well? Maybe it will be liked by millions - perhaps not. You'll never know until you <strong>share</strong>!</p>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Did Not Know That - Share Those Aha Moments</title>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag 'modernizr' %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
	
		<header>
			<%= render 'layouts/header' %>
		</header>
	
		<div class="container">
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
			<% end %>
			<%= yield %>
		</div>
		
		<footer>
			<%= render 'layouts/footer' %>
		</footer>
		
		<!-- Google Analytics -->
		<script type="text/javascript">
		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-39930297-1']);
		  _gaq.push(['_trackPageview']);
		  (function() {
		    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();
		</script>
	
	</body>
</html>

app/views/pages/about.html.erb
<!-- Main Body Content -->
<h1>About</h1>
<p>More information is on the way!</p>

app/views/pages/home.html.erb
<% if !user_signed_in? %>
	<p id="signUpNotice"><span class="label label-important">Please Note</span> You must be signed up to rank the posts below. Why not <%=link_to "Sign Up", new_user_registration_path %> now?</p>
<% end %>
<div class="row">
	<div class="span4">
		<h1>Latest</h1>
		<table id="pins" class="table table-striped">			
			<tbody>
				<%= render :partial => "pins/pinRating", :collection => @pins %>	
			</tbody>
		</table>
	</div>
	<div id="greatest" class="span4">
		<h1>Greatest</h1>
		<table id="pins" class="table table-striped">			
			<tbody>
				<%= render @pinsLikes %>
			</tbody>
		</table>
	</div>
	<div class="span3 offset1 hidden-phone">
		<% if user_signed_in? %>
			<h3>Member Links</h3>
			<%= link_to "Post a new Did-Not-Know-That", new_pin_path %><br />
			<%= link_to "See all my Did-Not-Know-Thats", pins_path %><br />
			<%= link_to "Email a suggesiton", "mailto:derrick@derrickshowers.com" %><br />
			<%= link_to "Logout", destroy_user_session_path %><br />
		<% else %>
			<h3>Sign in</h3>
	
			<%= simple_form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
			  
			  <%= f.error_notification %>
			  
			  <%= f.input :email %>
			  
			  <%= f.input :password %>
			  
			  <%= f.input :remember_me, as: :boolean, inline_label: 'Remember Me', label: false %>
			
			  <%= f.submit "Sign in", class: "btn btn-primary" %>
			
			<% end %>
			
			<%= link_to "Don't Have An Account?", new_registration_path(resource_name) %><br />
		<% end %>
	</div>
</div>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>
  
  <%= f.input :description, as: :text, input_html: { rows: "3" }, label: "Did Not Know..." %>
  <%= f.input :image, label: "(Optional) Add an image" %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<tr>
  <td><%= pin.description %></td>
  <td class="options">
  	<%= link_to (content_tag :i, "", class:"icon-search"), pin, :class => 'pull-right' %>
	  <% if current_user == pin.user %>
		  <%= link_to (content_tag :i, "", class:"icon-pencil"), edit_pin_path(pin), :class => 'pull-right' %>
		  <%= link_to (content_tag :i, "", class:"icon-trash"), pin, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'pull-right' %>
		  </td>
		<% else %>
		  </td>
		<% end %>
</tr>

app/views/pins/_pinRating.html.erb
<tr>
  <td><%= pinRating.description %></td>
  <td class="options">
  	<% if user_signed_in? %>
	  	<%= link_to (content_tag :i, "", class:"icon-thumbs-up"), { :controller => 'pins', :action => 'updateLikes', :id => pinRating.id, :like => true }, :method => :put, :remote => true, :class =>  (@likedPins.where(:pin_id => pinRating.id, :rating => 1).count > 0) ? "iconSelected likeDislike pull-right" : "likeDislike pull-right" %>
	  	<%= link_to (content_tag :i, "", class:"icon-thumbs-down"), { :controller => 'pins', :action => 'updateLikes', :id => pinRating.id }, :method => :put, :remote => true, :class => (@likedPins.where(:pin_id => pinRating.id, :rating => -1).count > 0) ? "iconSelected likeDislike pull-right" : "likeDislike pull-right" %>
	  <% end %>
	 </td>
</tr>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<h1>My Dashboard</h1>
<div class="row">
	<div id="myPins" class="span6">
		<table id="pins" class="table table-striped">
		  <thead>
			  <tr>
			    <th>My Did-Not-Know-Thats</th>
			    <th class="pull-right">Edit</th>
			  </tr>
		  </thead>
			<tbody>
				<%= render @myPins %>
			</tbody>
		</table>
		<a href="#myModal" role="button" class="btn btn-primary" data-toggle="modal">Did Not Know...</a>
		<% if @myPins.count <= 0 %>
			<div id="noPinsGetStarted"></div>
		<% end %>
	</div>
	<div class="span6">
		<table id="pins" class="table table-striped">
		  <thead>
			  <tr>
			    <th>Others' Did-Not-Know-Thats</th>
			    <th class="pull-right">Rate It</th>
			  </tr>
		  </thead>
			<tbody>
				<%= render :partial => 'pinRating', :collection => @otherPins %>
			</tbody>
		</table>
	</div>
</div>
	
	<br />

<% 
	#TODO: Show this if JS is disabled
	#link_to "Did Not Know...", new_pin_path, class:" btn btn-primary btn-large" 
%>
 
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Did Not Know...</h3>
  </div>
  <div class="modal-body">
    <%= render 'form' %>
  </div>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<% if @pin.image? %>
				<%= image_tag @pin.image %>
			<% end %>
			<p>
			  <%= @pin.description %>
			</p>
			<p>
			  <%= @pin.user.name %>
			</p>
			<% if current_user == @pin.user %>
				<%= link_to 'Edit', edit_pin_path(@pin) %> |
			<% end %>
			<%= link_to 'Back', pins_path %>
		</div>
	</div>
</div>